# Type stubs for common_types.tenant_middleware module
from typing import Any, AsyncGenerator, Dict, Optional
from sqlalchemy.ext.asyncio import AsyncSession
from starlette.middleware.base import BaseHTTPMiddleware
from fastapi import Request, Response

class TenantContext:
    tenant_id: str
    database_url: str
    request: Request
    
    def __init__(self, tenant_id: str, database_url: str, request: Request) -> None: ...

class TenantMiddleware(BaseHTTPMiddleware):
    def __init__(self) -> None: ...
    async def dispatch(self, request: Request, call_next: Any) -> Response: ...
    async def get_tenant_db_session(self, tenant_id: str, database_url: str) -> AsyncGenerator[AsyncSession, None]: ...

async def get_tenant_context() -> TenantContext: ...
async def get_tenant_db_session() -> AsyncGenerator[AsyncSession, None]: ...
async def check_tenant_routing_health() -> Dict[str, Any]: ...

def generate_tenant_jwt(user_id: str, tenant_id: str, expires_in: int = 3600) -> str: ...
def verify_tenant_jwt(token: str) -> Dict[str, Any]: ...
