from fastapi import FastAPI, HTTPException, status, Path
from typing import Dict

app = FastAPI(
    title="Localization Service",
    description="Provides translation strings for different locales.",
    version="1.0.0"
)

# --- "Database" for translations ---
# In a real app, this would come from a TMS (Translation Management System)
# like Lokalise or Crowdin, and be cached.
fake_translations_db = {
    "en-GB": {
        "common": {
            "submit": "Submit",
            "cancel": "Cancel",
            "logout": "Logout",
            "save": "Save",
            "loading": "Loading..."
        },
        "login": {
            "title": "Self Assessment Assistant",
            "description": "Register or log in to continue",
            "register_button": "Register",
            "login_button": "Login",
            "email_placeholder": "Email",
            "password_placeholder": "Password",
            "register_success": "Registration successful. You can now log in."
        },
        "nav": {
            "dashboard": "Dashboard",
            "activity": "Activity",
            "transactions": "Transactions",
            "documents": "Documents",
            "reports": "Reports",
            "marketplace": "Marketplace",
            "submission": "Tax Submission",
            "profile": "Profile",
            "admin": "Admin"
        },
        "dashboard": {
            "title": "Main Dashboard",
            "description": "Welcome to your Self-Assessment workspace.",
            "tax_estimator_title": "Tax Estimator (UK)",
            "tax_estimator_button": "Calculate Tax",
            "tax_estimator_result_title": "Estimated Tax for",
            "total_income_label": "Total Income",
            "allowable_expenses_label": "Allowable Expenses",
            "disallowable_expenses_label": "Disallowable Expenses",
            "taxable_profit_label": "Taxable Profit",
            "income_tax_due_label": "Income Tax",
            "class2_nic_label": "Class 2 NIC",
            "class4_nic_label": "Class 4 NIC",
            "estimated_tax_due_label": "Estimated Tax Due",
            "cashflow_title": "Cash Flow Forecast (Next 30 Days)",
            "cashflow_loading": "Generating forecast...",
            "readiness_title": "Tax Readiness Score",
            "readiness_description": "Shows how prepared your data is for Self-Assessment.",
            "readiness_score_label": "Readiness score",
            "readiness_missing_categories": "Uncategorised transactions:",
            "readiness_missing_business_use": "Missing business-use % on expenses:",
            "readiness_actions_title": "Next best actions",
            "readiness_action_categories": "Categorise remaining transactions.",
            "readiness_action_business_use": "Add business-use % for mixed expenses.",
            "readiness_no_transactions": "No transactions imported yet.",
            "readiness_low": "Low readiness",
            "readiness_medium": "Medium readiness",
            "readiness_high": "High readiness",
            "readiness_loading": "Calculating readiness...",
            "action_next_title": "What's next?",
            "action_next_description": "Explore our marketplace of trusted partners for insurance, accounting, and more.",
            "action_next_button": "Explore Partner Services"
        },
        "activity": {
            "description": "Here is a record of recent events in your account.",
            "col_date": "Date",
            "col_action": "Action",
            "col_details": "Details"
        },
        "transactions": {
            "title": "Transactions",
            "description": "Connect your bank account to import and categorize your transactions.",
            "bank_connections_title": "Bank Connections",
            "connect_button": "Connect a Bank Account",
            "consent_prompt": "Click the link to grant access at your bank:",
            "loading": "Loading transactions...",
            "recent_title": "Recent Transactions",
            "col_date": "Date",
            "col_description": "Description",
            "col_amount": "Amount",
            "col_category": "Category",
            "select_placeholder": "Select...",
            "csv_title": "CSV Import",
            "csv_description": "Upload a CSV file if your bank is not supported.",
            "csv_account_label": "Account ID",
            "csv_account_placeholder": "Paste account UUID",
            "csv_upload_button": "Upload CSV",
            "csv_uploading": "Uploading...",
            "csv_success": "CSV import accepted. Imported:",
            "csv_skipped_label": "Skipped:",
            "csv_select_error": "Please select a CSV file.",
            "csv_account_error": "Account ID is required."
        },
        "documents": {
            "description": "Upload and manage your receipts and invoices.",
            "upload_title": "Upload a Document",
            "upload_button": "Upload",
            "uploading_button": "Uploading...",
            "col_filename": "Filename",
            "col_status": "Status",
            "col_vendor": "Vendor",
            "col_amount": "Amount",
            "col_uploaded_at": "Uploaded At",
            "search_title": "Semantic Document Search",
            "search_description": "Ask a question about your documents in natural language.",
            "search_placeholder": "e.g., 'where did I buy coffee last month?'",
            "search_button": "Search",
            "search_results_title": "Search Results",
            "search_similarity_label": "Similarity score:",
            "all_documents_title": "All Uploaded Documents",
            "select_file_error": "Please select a file first.",
            "upload_success_prefix": "File uploaded:"
        },
        "reports": {
            "description": "Generate custom reports based on your financial data.",
            "cadence_title": "Reporting cadence",
            "cadence_description": "Based on turnover, determine whether quarterly reporting is required.",
            "cadence_turnover_label": "Turnover (last 12 months)",
            "cadence_threshold_label": "Quarterly threshold",
            "cadence_quarterly_required": "Quarterly reporting required.",
            "cadence_monthly_ok": "Monthly reporting is sufficient.",
            "monthly_title": "Monthly summary",
            "monthly_description": "Get a month-by-month profit summary.",
            "monthly_button": "Generate monthly summary",
            "quarterly_title": "Quarterly summary (Pro)",
            "quarterly_description": "Generate a quarterly summary if required.",
            "quarterly_button": "Generate quarterly summary",
            "profit_loss_title": "Profit & Loss (Pro)",
            "profit_loss_description": "Generate a profit & loss statement for the last quarter.",
            "profit_loss_button": "Generate profit & loss",
            "tax_year_title": "Tax year summary (Pro)",
            "tax_year_description": "Summary for the UK tax year.",
            "tax_year_button": "Generate tax year summary",
            "mortgage_title": "Mortgage Readiness Report",
            "mortgage_description": "Generate a PDF summary of your income over the last 12 months. This can be useful when applying for a mortgage.",
            "generate_button": "Generate Report",
            "generating_button": "Generating...",
            "pro_required": "Pro subscription required.",
            "error_generic": "Failed to generate report."
        },
        "marketplace": {
            "description": "Discover our marketplace of trusted partners for accounting, insurance, and more.",
            "request_button": "Request Contact",
            "handoff_confirmation": "Your request has been sent to"
        },
        "submission": {
            "description": "Calculate and submit your tax return to HMRC.",
            "form_title": "New UK Tax Submission",
            "submit_button": "Calculate & Submit to HMRC",
            "success_title": "Submission Successfully Initiated",
            "submitting": "Submitting...",
            "status_label": "Submission Status",
            "id_label": "HMRC Submission ID",
            "reminder_note": "We've added a calendar reminder for the 31 January payment deadline."
        },
        "profile": {
            "title": "Your Profile",
            "description": "Review and update your profile details.",
            "empty_profile": "No profile found. Create one by saving.",
            "saved_message": "Profile saved successfully!",
            "first_name": "First Name",
            "last_name": "Last Name",
            "date_of_birth": "Date of Birth"
        },
        "subscription": {
            "title": "Subscription",
            "description": "Manage your plan and monthly close day.",
            "plan_label": "Plan",
            "plan_free": "Free",
            "plan_pro": "Pro",
            "close_day_label": "Monthly close day (1-28)",
            "status_label": "Status",
            "cycle_label": "Billing cycle",
            "period_label": "Current period",
            "update_button": "Update subscription",
            "updated_message": "Subscription updated."
        },
        "admin": {
            "description": "Manage users and system settings.",
            "form_title": "Deactivate a User",
            "deactivate_button": "Deactivate User",
            "email_placeholder": "user.email@example.com",
            "deactivated_message": "User deactivated:"
        }
    },
    "de-DE": {
        "common": {
            "submit": "Einreichen",
            "cancel": "Abbrechen",
            "logout": "Ausloggen",
            "save": "Speichern",
            "loading": "Wird geladen..."
        },
        "login": {
            "title": "Self-Assessment Assistent",
            "description": "Registrieren Sie sich oder melden Sie sich an, um fortzufahren",
            "register_button": "Registrieren",
            "login_button": "Anmelden",
            "email_placeholder": "E-Mail",
            "password_placeholder": "Passwort",
            "register_success": "Registrierung erfolgreich. Sie können sich jetzt anmelden."
        },
        "nav": {
            "dashboard": "Dashboard",
            "activity": "Aktivitätsprotokoll",
            "transactions": "Transaktionen",
            "documents": "Dokumente",
            "reports": "Berichte",
            "marketplace": "Marktplatz",
            "submission": "HMRC-Übermittlung",
            "profile": "Profil",
            "admin": "Admin"
        },
        "dashboard": {
            "title": "Haupt-Dashboard",
            "description": "Willkommen in Ihrem Self-Assessment-Arbeitsbereich.",
            "tax_estimator_title": "Steuerschätzer (UK)",
            "tax_estimator_button": "Steuer berechnen",
            "tax_estimator_result_title": "Geschätzte Steuer für",
            "total_income_label": "Gesamteinnahmen",
            "allowable_expenses_label": "Abzugsfähige Ausgaben",
            "disallowable_expenses_label": "Nicht abzugsfähige Ausgaben",
            "taxable_profit_label": "Steuerpflichtiger Gewinn",
            "income_tax_due_label": "Einkommensteuer",
            "class2_nic_label": "Class 2 NIC",
            "class4_nic_label": "Class 4 NIC",
            "estimated_tax_due_label": "Voraussichtliche Steuer",
            "cashflow_title": "Cashflow-Prognose (nächste 30 Tage)",
            "cashflow_loading": "Prognose wird erstellt...",
            "readiness_title": "Steuerbereitschaft",
            "readiness_description": "Zeigt, wie gut Ihre Daten für Self-Assessment vorbereitet sind.",
            "readiness_score_label": "Bereitschaftswert",
            "readiness_missing_categories": "Nicht kategorisierte Transaktionen:",
            "readiness_missing_business_use": "Fehlender Geschäftsanteil bei Ausgaben:",
            "readiness_actions_title": "Nächste Schritte",
            "readiness_action_categories": "Restliche Transaktionen kategorisieren.",
            "readiness_action_business_use": "Geschäftsanteil für gemischte Ausgaben ergänzen.",
            "readiness_no_transactions": "Noch keine Transaktionen importiert.",
            "readiness_low": "Niedrige Bereitschaft",
            "readiness_medium": "Mittlere Bereitschaft",
            "readiness_high": "Hohe Bereitschaft",
            "readiness_loading": "Bereitschaft wird berechnet...",
            "action_next_title": "Was kommt als Nächstes?",
            "action_next_description": "Entdecken Sie unseren Marktplatz mit vertrauenswürdigen Partnern für Versicherungen, Buchhaltung und mehr.",
            "action_next_button": "Partnerdienste entdecken"
        },
        "activity": {
            "description": "Hier ist eine Aufzeichnung der letzten wichtigen Ereignisse in Ihrem Konto.",
            "col_date": "Datum",
            "col_action": "Aktion",
            "col_details": "Details"
        },
        "transactions": {
            "title": "Transaktionen",
            "description": "Verbinden Sie Ihr Bankkonto, um Transaktionen zu importieren und zu kategorisieren.",
            "bank_connections_title": "Bankverbindungen",
            "connect_button": "Bankkonto verbinden",
            "consent_prompt": "Klicken Sie auf den Link, um Zugriff bei Ihrer Bank zu gewähren:",
            "loading": "Transaktionen werden geladen...",
            "recent_title": "Letzte Transaktionen",
            "col_date": "Datum",
            "col_description": "Beschreibung",
            "col_amount": "Betrag",
            "col_category": "Kategorie",
            "select_placeholder": "Auswählen...",
            "csv_title": "CSV-Import",
            "csv_description": "Laden Sie eine CSV-Datei hoch, wenn Ihre Bank nicht unterstützt wird.",
            "csv_account_label": "Konto-ID",
            "csv_account_placeholder": "Konto-UUID einfügen",
            "csv_upload_button": "CSV hochladen",
            "csv_uploading": "Wird hochgeladen...",
            "csv_success": "CSV-Import akzeptiert. Importiert:",
            "csv_skipped_label": "Übersprungen:",
            "csv_select_error": "Bitte wählen Sie eine CSV-Datei aus.",
            "csv_account_error": "Konto-ID ist erforderlich."
        },
        "documents": {
            "description": "Laden Sie Ihre Belege und Rechnungen hoch und verwalten Sie sie.",
            "upload_title": "Dokument hochladen",
            "upload_button": "Hochladen",
            "uploading_button": "Lädt hoch...",
            "col_filename": "Dateiname",
            "col_status": "Status",
            "col_vendor": "Anbieter",
            "col_amount": "Betrag",
            "col_uploaded_at": "Hochgeladen am",
            "search_title": "Semantische Dokumentsuche",
            "search_description": "Stellen Sie eine Frage zu Ihren Dokumenten in natürlicher Sprache.",
            "search_placeholder": "z.B. 'wo habe ich letzten monat kaffee gekauft?'",
            "search_button": "Suchen",
            "search_results_title": "Suchergebnisse",
            "search_similarity_label": "Ähnlichkeitswert:",
            "all_documents_title": "Alle hochgeladenen Dokumente",
            "select_file_error": "Bitte wählen Sie zuerst eine Datei aus.",
            "upload_success_prefix": "Datei hochgeladen:"
        },
        "reports": {
            "description": "Erstellen Sie benutzerdefinierte Berichte basierend auf Ihren Finanzdaten.",
            "cadence_title": "Meldezyklus",
            "cadence_description": "Bestimmt, ob eine quartalsweise Meldung erforderlich ist.",
            "cadence_turnover_label": "Umsatz (letzte 12 Monate)",
            "cadence_threshold_label": "Quartals-Schwelle",
            "cadence_quarterly_required": "Quartalsweise Berichte erforderlich.",
            "cadence_monthly_ok": "Monatliche Berichte reichen aus.",
            "monthly_title": "Monatsübersicht",
            "monthly_description": "Monatliche Gewinnübersicht abrufen.",
            "monthly_button": "Monatsübersicht erstellen",
            "quarterly_title": "Quartalsübersicht (Pro)",
            "quarterly_description": "Quartalsbericht erstellen, falls erforderlich.",
            "quarterly_button": "Quartalsübersicht erstellen",
            "profit_loss_title": "Gewinn & Verlust (Pro)",
            "profit_loss_description": "GuV für das letzte Quartal erstellen.",
            "profit_loss_button": "GuV erstellen",
            "tax_year_title": "Steuerjahresübersicht (Pro)",
            "tax_year_description": "Zusammenfassung für das UK-Steuerjahr.",
            "tax_year_button": "Steuerjahresübersicht erstellen",
            "mortgage_title": "Bericht zur Hypothekenbereitschaft",
            "mortgage_description": "Erstellen Sie eine PDF-Zusammenfassung Ihres Einkommens der letzten 12 Monate. Dies kann bei der Beantragung einer Hypothek nützlich sein.",
            "generate_button": "Bericht erstellen",
            "generating_button": "Wird erstellt...",
            "pro_required": "Pro-Abonnement erforderlich.",
            "error_generic": "Bericht konnte nicht erstellt werden."
        },
        "marketplace": {
            "description": "Entdecken Sie unseren Marktplatz mit vertrauenswürdigen Partnern für Buchhaltung, Versicherungen und mehr.",
            "request_button": "Kontakt anfragen",
            "handoff_confirmation": "Ihre Anfrage wurde gesendet an"
        },
        "submission": {
            "description": "Berechnen und übermitteln Sie hier Ihre Steuererklärung an HMRC.",
            "form_title": "Neue Steuererklärung für Großbritannien",
            "submit_button": "Berechnen & an HMRC senden",
            "success_title": "Übermittlung erfolgreich eingeleitet",
            "submitting": "Wird gesendet...",
            "status_label": "Übermittlungsstatus",
            "id_label": "HMRC-Übermittlungs-ID",
            "reminder_note": "Wir haben eine Kalendereinladung für die Zahlungsfrist am 31. Januar hinzugefügt."
        },
        "profile": {
            "title": "Ihr Profil",
            "description": "Überprüfen und aktualisieren Sie Ihre Profildaten.",
            "empty_profile": "Kein Profil gefunden. Speichern Sie, um eines zu erstellen.",
            "saved_message": "Profil erfolgreich gespeichert!",
            "first_name": "Vorname",
            "last_name": "Nachname",
            "date_of_birth": "Geburtsdatum"
        },
        "subscription": {
            "title": "Abonnement",
            "description": "Plan und monatlichen Abschluss verwalten.",
            "plan_label": "Plan",
            "plan_free": "Free",
            "plan_pro": "Pro",
            "close_day_label": "Monatlicher Abschlusstag (1-28)",
            "status_label": "Status",
            "cycle_label": "Abrechnungszyklus",
            "period_label": "Aktueller Zeitraum",
            "update_button": "Abonnement aktualisieren",
            "updated_message": "Abonnement aktualisiert."
        },
        "admin": {
            "description": "Benutzer und Systemeinstellungen verwalten.",
            "form_title": "Einen Benutzer deaktivieren",
            "deactivate_button": "Benutzer deaktivieren",
            "email_placeholder": "user.email@example.com",
            "deactivated_message": "Benutzer deaktiviert:"
        }
    },
    "ru-RU": {
        "common": {
            "submit": "Отправить",
            "cancel": "Отмена",
            "logout": "Выйти",
            "save": "Сохранить",
            "loading": "Загрузка..."
        },
        "login": {
            "title": "Помощник по Self-Assessment",
            "description": "Зарегистрируйтесь или войдите, чтобы продолжить",
            "register_button": "Регистрация",
            "login_button": "Войти",
            "email_placeholder": "Email",
            "password_placeholder": "Пароль",
            "register_success": "Регистрация успешна. Теперь можно войти."
        },
        "nav": {
            "dashboard": "Дашборд",
            "activity": "Активность",
            "transactions": "Транзакции",
            "documents": "Документы",
            "reports": "Отчеты",
            "marketplace": "Маркетплейс",
            "submission": "Подача налогов",
            "profile": "Профиль",
            "admin": "Админ"
        },
        "dashboard": {
            "title": "Главная панель",
            "description": "Добро пожаловать в ваш Self-Assessment.",
            "tax_estimator_title": "Оценка налога (UK)",
            "tax_estimator_button": "Рассчитать налог",
            "tax_estimator_result_title": "Оценка налога за",
            "total_income_label": "Общий доход",
            "allowable_expenses_label": "Допустимые расходы",
            "disallowable_expenses_label": "Недопустимые расходы",
            "taxable_profit_label": "Налогооблагаемая прибыль",
            "income_tax_due_label": "Подоходный налог",
            "class2_nic_label": "Class 2 NIC",
            "class4_nic_label": "Class 4 NIC",
            "estimated_tax_due_label": "Итого к уплате",
            "cashflow_title": "Прогноз денежного потока (30 дней)",
            "cashflow_loading": "Формируем прогноз...",
            "readiness_title": "Готовность к сдаче",
            "readiness_description": "Показывает готовность данных к Self-Assessment.",
            "readiness_score_label": "Индекс готовности",
            "readiness_missing_categories": "Без категории:",
            "readiness_missing_business_use": "Нет процента бизнес-использования:",
            "readiness_actions_title": "Следующие шаги",
            "readiness_action_categories": "Категоризируйте оставшиеся транзакции.",
            "readiness_action_business_use": "Укажите бизнес-долю для смешанных расходов.",
            "readiness_no_transactions": "Транзакции еще не импортированы.",
            "readiness_low": "Низкая готовность",
            "readiness_medium": "Средняя готовность",
            "readiness_high": "Высокая готовность",
            "readiness_loading": "Считаем готовность...",
            "action_next_title": "Что дальше?",
            "action_next_description": "Посмотрите маркетплейс с проверенными партнерами для страховки, бухгалтерии и другого.",
            "action_next_button": "Перейти к партнерам"
        },
        "activity": {
            "description": "Журнал последних событий в вашем аккаунте.",
            "col_date": "Дата",
            "col_action": "Действие",
            "col_details": "Детали"
        },
        "transactions": {
            "title": "Транзакции",
            "description": "Подключите банк, чтобы импортировать и категоризировать транзакции.",
            "bank_connections_title": "Банковские подключения",
            "connect_button": "Подключить банк",
            "consent_prompt": "Нажмите ссылку, чтобы дать доступ банку:",
            "loading": "Загружаем транзакции...",
            "recent_title": "Последние транзакции",
            "col_date": "Дата",
            "col_description": "Описание",
            "col_amount": "Сумма",
            "col_category": "Категория",
            "select_placeholder": "Выбрать...",
            "csv_title": "CSV импорт",
            "csv_description": "Загрузите CSV, если банк не поддерживается.",
            "csv_account_label": "Account ID",
            "csv_account_placeholder": "Вставьте UUID счета",
            "csv_upload_button": "Загрузить CSV",
            "csv_uploading": "Загружаем...",
            "csv_success": "CSV импорт принят. Импортировано:",
            "csv_skipped_label": "Пропущено:",
            "csv_select_error": "Выберите CSV файл.",
            "csv_account_error": "Нужен Account ID."
        },
        "documents": {
            "description": "Загружайте и храните чеки и счета.",
            "upload_title": "Загрузить документ",
            "upload_button": "Загрузить",
            "uploading_button": "Загрузка...",
            "col_filename": "Файл",
            "col_status": "Статус",
            "col_vendor": "Поставщик",
            "col_amount": "Сумма",
            "col_uploaded_at": "Загружено",
            "search_title": "Семантический поиск документов",
            "search_description": "Задайте вопрос к вашим документам на естественном языке.",
            "search_placeholder": "например, «где я купил кофе в прошлом месяце?»",
            "search_button": "Искать",
            "search_results_title": "Результаты поиска",
            "search_similarity_label": "Схожесть:",
            "all_documents_title": "Все документы",
            "select_file_error": "Сначала выберите файл.",
            "upload_success_prefix": "Файл загружен:"
        },
        "reports": {
            "description": "Создавайте отчеты на основе финансовых данных.",
            "cadence_title": "Периодичность отчётности",
            "cadence_description": "Определяет необходимость квартальной отчетности.",
            "cadence_turnover_label": "Оборот за 12 месяцев",
            "cadence_threshold_label": "Порог квартальной отчетности",
            "cadence_quarterly_required": "Нужна квартальная отчетность.",
            "cadence_monthly_ok": "Достаточно ежемесячной отчетности.",
            "monthly_title": "Ежемесячный отчет",
            "monthly_description": "Сводка прибыли за месяц.",
            "monthly_button": "Сформировать месяц",
            "quarterly_title": "Квартальный отчет (Pro)",
            "quarterly_description": "Квартальная сводка при необходимости.",
            "quarterly_button": "Сформировать квартал",
            "profit_loss_title": "Прибыли и убытки (Pro)",
            "profit_loss_description": "Отчет P&L за последний квартал.",
            "profit_loss_button": "Сформировать P&L",
            "tax_year_title": "Отчет за налоговый год (Pro)",
            "tax_year_description": "Сводка по налоговому году UK.",
            "tax_year_button": "Сформировать налоговый год",
            "mortgage_title": "Отчет для ипотеки",
            "mortgage_description": "PDF-сводка доходов за 12 месяцев.",
            "generate_button": "Сформировать отчет",
            "generating_button": "Формируется...",
            "pro_required": "Нужна подписка Pro.",
            "error_generic": "Не удалось сформировать отчет."
        },
        "marketplace": {
            "description": "Партнеры для бухгалтерии, страховки и прочего.",
            "request_button": "Запросить контакт",
            "handoff_confirmation": "Запрос отправлен партнеру"
        },
        "submission": {
            "description": "Рассчитать и отправить декларацию в HMRC.",
            "form_title": "Новая подача UK Self-Assessment",
            "submit_button": "Рассчитать и отправить в HMRC",
            "success_title": "Подача начата",
            "submitting": "Отправляем...",
            "status_label": "Статус подачи",
            "id_label": "ID подачи HMRC",
            "reminder_note": "Мы добавили напоминание в календарь о платеже до 31 января."
        },
        "profile": {
            "title": "Профиль",
            "description": "Обновите свои персональные данные.",
            "empty_profile": "Профиль не найден. Создайте его, сохранив данные.",
            "saved_message": "Профиль сохранен.",
            "first_name": "Имя",
            "last_name": "Фамилия",
            "date_of_birth": "Дата рождения"
        },
        "subscription": {
            "title": "Подписка",
            "description": "Управляйте планом и датой месячного закрытия.",
            "plan_label": "План",
            "plan_free": "Free",
            "plan_pro": "Pro",
            "close_day_label": "День закрытия месяца (1-28)",
            "status_label": "Статус",
            "cycle_label": "Период оплаты",
            "period_label": "Текущий период",
            "update_button": "Обновить подписку",
            "updated_message": "Подписка обновлена."
        },
        "admin": {
            "description": "Управление пользователями и настройками.",
            "form_title": "Деактивация пользователя",
            "deactivate_button": "Деактивировать",
            "email_placeholder": "user.email@example.com",
            "deactivated_message": "Пользователь деактивирован:"
        }
    },
    "ro-MD": {
        "common": {
            "submit": "Trimite",
            "cancel": "Anulează",
            "logout": "Deconectare",
            "save": "Salvează",
            "loading": "Se încarcă..."
        },
        "login": {
            "title": "Asistent Self Assessment",
            "description": "Înregistrează-te sau autentifică-te pentru a continua",
            "register_button": "Înregistrează-te",
            "login_button": "Autentificare",
            "email_placeholder": "Email",
            "password_placeholder": "Parolă",
            "register_success": "Înregistrare reușită. Te poți autentifica."
        },
        "nav": {
            "dashboard": "Panou",
            "activity": "Activitate",
            "transactions": "Tranzacții",
            "documents": "Documente",
            "reports": "Rapoarte",
            "marketplace": "Marketplace",
            "submission": "Depunere taxe",
            "profile": "Profil",
            "admin": "Admin"
        },
        "dashboard": {
            "title": "Panou principal",
            "description": "Bun venit în spațiul tău Self Assessment.",
            "tax_estimator_title": "Estimator taxe (UK)",
            "tax_estimator_button": "Calculează taxele",
            "tax_estimator_result_title": "Taxă estimată pentru",
            "total_income_label": "Venit total",
            "allowable_expenses_label": "Cheltuieli deductibile",
            "disallowable_expenses_label": "Cheltuieli nedeductibile",
            "taxable_profit_label": "Profit impozabil",
            "income_tax_due_label": "Impozit pe venit",
            "class2_nic_label": "NIC clasa 2",
            "class4_nic_label": "NIC clasa 4",
            "estimated_tax_due_label": "Taxă estimată",
            "cashflow_title": "Previziune flux de numerar (următoarele 30 de zile)",
            "cashflow_loading": "Se generează prognoza...",
            "readiness_title": "Scor de pregătire fiscală",
            "readiness_description": "Arată cât de pregătite sunt datele pentru Self Assessment.",
            "readiness_score_label": "Scor de pregătire",
            "readiness_missing_categories": "Tranzacții necategorizate:",
            "readiness_missing_business_use": "Lipsă procent business la cheltuieli:",
            "readiness_actions_title": "Următorii pași",
            "readiness_action_categories": "Categorisește tranzacțiile rămase.",
            "readiness_action_business_use": "Adaugă % business pentru cheltuieli mixte.",
            "readiness_no_transactions": "Nu există încă tranzacții importate.",
            "readiness_low": "Pregătire scăzută",
            "readiness_medium": "Pregătire medie",
            "readiness_high": "Pregătire ridicată",
            "readiness_loading": "Se calculează pregătirea...",
            "action_next_title": "Ce urmează?",
            "action_next_description": "Explorează marketplace-ul nostru de parteneri pentru asigurări, contabilitate și altele.",
            "action_next_button": "Explorează servicii partenere"
        },
        "activity": {
            "description": "Iată o înregistrare a activităților recente din contul tău.",
            "col_date": "Data",
            "col_action": "Acțiune",
            "col_details": "Detalii"
        },
        "transactions": {
            "title": "Tranzacții",
            "description": "Conectează contul bancar pentru a importa și categorisi tranzacțiile.",
            "bank_connections_title": "Conexiuni bancare",
            "connect_button": "Conectează un cont bancar",
            "consent_prompt": "Apasă linkul pentru a acorda acces la banca ta:",
            "loading": "Se încarcă tranzacțiile...",
            "recent_title": "Tranzacții recente",
            "col_date": "Data",
            "col_description": "Descriere",
            "col_amount": "Sumă",
            "col_category": "Categorie",
            "select_placeholder": "Selectează...",
            "csv_title": "Import CSV",
            "csv_description": "Încarcă un fișier CSV dacă banca nu este suportată.",
            "csv_account_label": "ID cont",
            "csv_account_placeholder": "Lipește UUID-ul contului",
            "csv_upload_button": "Încarcă CSV",
            "csv_uploading": "Se încarcă...",
            "csv_success": "Import CSV acceptat. Importate:",
            "csv_skipped_label": "Omise:",
            "csv_select_error": "Selectează un fișier CSV.",
            "csv_account_error": "ID-ul contului este obligatoriu."
        },
        "documents": {
            "description": "Încarcă și gestionează chitanțe și facturi.",
            "upload_title": "Încarcă un document",
            "upload_button": "Încarcă",
            "uploading_button": "Se încarcă...",
            "col_filename": "Nume fișier",
            "col_status": "Stare",
            "col_vendor": "Furnizor",
            "col_amount": "Sumă",
            "col_uploaded_at": "Încărcat la",
            "search_title": "Căutare semantică în documente",
            "search_description": "Pune o întrebare despre documentele tale în limbaj natural.",
            "search_placeholder": "ex: 'unde am cumpărat cafea luna trecută?'",
            "search_button": "Caută",
            "search_results_title": "Rezultate căutare",
            "search_similarity_label": "Scor similaritate:",
            "all_documents_title": "Toate documentele încărcate",
            "select_file_error": "Te rugăm să selectezi mai întâi un fișier.",
            "upload_success_prefix": "Fișier încărcat:"
        },
        "reports": {
            "description": "Generează rapoarte personalizate pe baza datelor tale.",
            "cadence_title": "Cadență de raportare",
            "cadence_description": "Pe baza cifrei de afaceri, determină dacă este necesară raportarea trimestrială.",
            "cadence_turnover_label": "Cifră de afaceri (ultimele 12 luni)",
            "cadence_threshold_label": "Prag trimestrial",
            "cadence_quarterly_required": "Raportare trimestrială necesară.",
            "cadence_monthly_ok": "Raportarea lunară este suficientă.",
            "monthly_title": "Sumar lunar",
            "monthly_description": "Obține un sumar lunar al profitului.",
            "monthly_button": "Generează sumar lunar",
            "quarterly_title": "Sumar trimestrial (Pro)",
            "quarterly_description": "Generează sumar trimestrial dacă este necesar.",
            "quarterly_button": "Generează sumar trimestrial",
            "profit_loss_title": "Profit & pierdere (Pro)",
            "profit_loss_description": "Generează P&L pentru ultimul trimestru.",
            "profit_loss_button": "Generează profit & pierdere",
            "tax_year_title": "Sumar an fiscal (Pro)",
            "tax_year_description": "Sumar pentru anul fiscal UK.",
            "tax_year_button": "Generează sumar an fiscal",
            "mortgage_title": "Raport pregătire ipotecă",
            "mortgage_description": "Generează un PDF al veniturilor din ultimele 12 luni. Util pentru aplicații de ipotecă.",
            "generate_button": "Generează raport",
            "generating_button": "Se generează...",
            "pro_required": "Este necesar abonament Pro.",
            "error_generic": "Nu s-a putut genera raportul."
        },
        "marketplace": {
            "description": "Descoperă marketplace-ul nostru de parteneri pentru contabilitate, asigurări și altele.",
            "request_button": "Solicită contact",
            "handoff_confirmation": "Cererea ta a fost trimisă către"
        },
        "submission": {
            "description": "Calculează și trimite declarația fiscală către HMRC.",
            "form_title": "Depunere nouă Self Assessment UK",
            "submit_button": "Calculează și trimite către HMRC",
            "success_title": "Depunere inițiată cu succes",
            "submitting": "Se trimite...",
            "status_label": "Stare depunere",
            "id_label": "ID depunere HMRC",
            "reminder_note": "Am adăugat un reminder în calendar pentru termenul de plată 31 ianuarie."
        },
        "profile": {
            "title": "Profilul tău",
            "description": "Revizuiește și actualizează datele profilului.",
            "empty_profile": "Nu s-a găsit profil. Salvează pentru a crea unul.",
            "saved_message": "Profil salvat cu succes!",
            "first_name": "Prenume",
            "last_name": "Nume",
            "date_of_birth": "Data nașterii"
        },
        "subscription": {
            "title": "Abonament",
            "description": "Gestionează planul și ziua de închidere lunară.",
            "plan_label": "Plan",
            "plan_free": "Gratuit",
            "plan_pro": "Pro",
            "close_day_label": "Zi de închidere lunară (1-28)",
            "status_label": "Stare",
            "cycle_label": "Ciclu de facturare",
            "period_label": "Perioadă curentă",
            "update_button": "Actualizează abonamentul",
            "updated_message": "Abonament actualizat."
        },
        "admin": {
            "description": "Gestionează utilizatori și setări de sistem.",
            "form_title": "Dezactivează un utilizator",
            "deactivate_button": "Dezactivează utilizator",
            "email_placeholder": "user.email@example.com",
            "deactivated_message": "Utilizator dezactivat:"
        }
    },
    "uk-UA": {
        "common": {
            "submit": "Надіслати",
            "cancel": "Скасувати",
            "logout": "Вийти",
            "save": "Зберегти",
            "loading": "Завантаження..."
        },
        "login": {
            "title": "Асистент Self Assessment",
            "description": "Зареєструйтесь або увійдіть, щоб продовжити",
            "register_button": "Зареєструватися",
            "login_button": "Увійти",
            "email_placeholder": "Email",
            "password_placeholder": "Пароль",
            "register_success": "Реєстрація успішна. Тепер можна увійти."
        },
        "nav": {
            "dashboard": "Панель",
            "activity": "Активність",
            "transactions": "Транзакції",
            "documents": "Документи",
            "reports": "Звіти",
            "marketplace": "Маркетплейс",
            "submission": "Подання податків",
            "profile": "Профіль",
            "admin": "Адмін"
        },
        "dashboard": {
            "title": "Головна панель",
            "description": "Ласкаво просимо до вашого Self Assessment.",
            "tax_estimator_title": "Оцінка податку (UK)",
            "tax_estimator_button": "Розрахувати податок",
            "tax_estimator_result_title": "Оціночний податок за",
            "total_income_label": "Загальний дохід",
            "allowable_expenses_label": "Допустимі витрати",
            "disallowable_expenses_label": "Недопустимі витрати",
            "taxable_profit_label": "Оподатковуваний прибуток",
            "income_tax_due_label": "Податок на дохід",
            "class2_nic_label": "NIC клас 2",
            "class4_nic_label": "NIC клас 4",
            "estimated_tax_due_label": "Оціночний податок",
            "cashflow_title": "Прогноз грошового потоку (наступні 30 днів)",
            "cashflow_loading": "Формується прогноз...",
            "readiness_title": "Оцінка готовності",
            "readiness_description": "Показує, наскільки підготовлені ваші дані для Self Assessment.",
            "readiness_score_label": "Оцінка готовності",
            "readiness_missing_categories": "Некатегоризовані транзакції:",
            "readiness_missing_business_use": "Відсутній бізнес-відсоток у витрат:",
            "readiness_actions_title": "Наступні кроки",
            "readiness_action_categories": "Категоризуйте решту транзакцій.",
            "readiness_action_business_use": "Додайте бізнес-відсоток для змішаних витрат.",
            "readiness_no_transactions": "Транзакції ще не імпортовані.",
            "readiness_low": "Низька готовність",
            "readiness_medium": "Середня готовність",
            "readiness_high": "Висока готовність",
            "readiness_loading": "Обчислення готовності...",
            "action_next_title": "Що далі?",
            "action_next_description": "Дослідіть наш маркетплейс перевірених партнерів для страхування, бухгалтерії тощо.",
            "action_next_button": "Переглянути партнерські сервіси"
        },
        "activity": {
            "description": "Ось запис останніх подій у вашому акаунті.",
            "col_date": "Дата",
            "col_action": "Дія",
            "col_details": "Деталі"
        },
        "transactions": {
            "title": "Транзакції",
            "description": "Підключіть банк, щоб імпортувати та категоризувати транзакції.",
            "bank_connections_title": "Банківські підключення",
            "connect_button": "Підключити банківський рахунок",
            "consent_prompt": "Натисніть посилання, щоб надати доступ у вашому банку:",
            "loading": "Завантаження транзакцій...",
            "recent_title": "Останні транзакції",
            "col_date": "Дата",
            "col_description": "Опис",
            "col_amount": "Сума",
            "col_category": "Категорія",
            "select_placeholder": "Виберіть...",
            "csv_title": "Імпорт CSV",
            "csv_description": "Завантажте CSV, якщо ваша банка не підтримується.",
            "csv_account_label": "ID рахунку",
            "csv_account_placeholder": "Вставте UUID рахунку",
            "csv_upload_button": "Завантажити CSV",
            "csv_uploading": "Завантаження...",
            "csv_success": "Імпорт CSV прийнято. Імпортовано:",
            "csv_skipped_label": "Пропущено:",
            "csv_select_error": "Виберіть CSV файл.",
            "csv_account_error": "ID рахунку обов'язковий."
        },
        "documents": {
            "description": "Завантажуйте та керуйте чеками й рахунками.",
            "upload_title": "Завантажити документ",
            "upload_button": "Завантажити",
            "uploading_button": "Завантаження...",
            "col_filename": "Назва файлу",
            "col_status": "Статус",
            "col_vendor": "Постачальник",
            "col_amount": "Сума",
            "col_uploaded_at": "Завантажено",
            "search_title": "Семантичний пошук документів",
            "search_description": "Поставте питання про документи природною мовою.",
            "search_placeholder": "наприклад, 'де я купив каву минулого місяця?'",
            "search_button": "Пошук",
            "search_results_title": "Результати пошуку",
            "search_similarity_label": "Показник схожості:",
            "all_documents_title": "Усі завантажені документи",
            "select_file_error": "Спочатку виберіть файл.",
            "upload_success_prefix": "Файл завантажено:"
        },
        "reports": {
            "description": "Створюйте кастомні звіти на основі фінансових даних.",
            "cadence_title": "Періодичність звітів",
            "cadence_description": "На основі обороту визначається, чи потрібна квартальна звітність.",
            "cadence_turnover_label": "Оборот (останні 12 місяців)",
            "cadence_threshold_label": "Квартальний поріг",
            "cadence_quarterly_required": "Потрібна квартальна звітність.",
            "cadence_monthly_ok": "Місячної звітності достатньо.",
            "monthly_title": "Місячний підсумок",
            "monthly_description": "Отримайте місячний підсумок прибутку.",
            "monthly_button": "Згенерувати місячний підсумок",
            "quarterly_title": "Квартальний підсумок (Pro)",
            "quarterly_description": "Згенерувати квартальний підсумок за потреби.",
            "quarterly_button": "Згенерувати квартальний підсумок",
            "profit_loss_title": "Прибуток і збитки (Pro)",
            "profit_loss_description": "Згенерувати P&L за останній квартал.",
            "profit_loss_button": "Згенерувати P&L",
            "tax_year_title": "Підсумок податкового року (Pro)",
            "tax_year_description": "Підсумок для податкового року UK.",
            "tax_year_button": "Згенерувати підсумок року",
            "mortgage_title": "Звіт для іпотеки",
            "mortgage_description": "Згенеруйте PDF-підсумок доходів за 12 місяців. Корисно для іпотеки.",
            "generate_button": "Згенерувати звіт",
            "generating_button": "Генерується...",
            "pro_required": "Потрібна підписка Pro.",
            "error_generic": "Не вдалося згенерувати звіт."
        },
        "marketplace": {
            "description": "Відкрийте наш маркетплейс партнерів з бухгалтерії, страхування та іншого.",
            "request_button": "Запросити контакт",
            "handoff_confirmation": "Ваш запит надіслано"
        },
        "submission": {
            "description": "Розрахуйте та подайте декларацію до HMRC.",
            "form_title": "Нова подача Self Assessment UK",
            "submit_button": "Розрахувати й подати до HMRC",
            "success_title": "Подача успішно ініційована",
            "submitting": "Відправляємо...",
            "status_label": "Статус подачі",
            "id_label": "ID подачі HMRC",
            "reminder_note": "Ми додали нагадування в календар про платіж до 31 січня."
        },
        "profile": {
            "title": "Ваш профіль",
            "description": "Перегляньте та оновіть дані профілю.",
            "empty_profile": "Профіль не знайдено. Створіть його, зберігши дані.",
            "saved_message": "Профіль успішно збережено!",
            "first_name": "Ім'я",
            "last_name": "Прізвище",
            "date_of_birth": "Дата народження"
        },
        "subscription": {
            "title": "Підписка",
            "description": "Керуйте планом і днем місячного закриття.",
            "plan_label": "План",
            "plan_free": "Безкоштовно",
            "plan_pro": "Pro",
            "close_day_label": "День місячного закриття (1-28)",
            "status_label": "Статус",
            "cycle_label": "Платіжний цикл",
            "period_label": "Поточний період",
            "update_button": "Оновити підписку",
            "updated_message": "Підписку оновлено."
        },
        "admin": {
            "description": "Керування користувачами та системними налаштуваннями.",
            "form_title": "Деактивація користувача",
            "deactivate_button": "Деактивувати користувача",
            "email_placeholder": "user.email@example.com",
            "deactivated_message": "Користувача деактивовано:"
        }
    },
    "pl-PL": {
        "common": {
            "submit": "Wyślij",
            "cancel": "Anuluj",
            "logout": "Wyloguj",
            "save": "Zapisz",
            "loading": "Ładowanie..."
        },
        "login": {
            "title": "Asystent Self Assessment",
            "description": "Zarejestruj się lub zaloguj, aby kontynuować",
            "register_button": "Zarejestruj się",
            "login_button": "Zaloguj się",
            "email_placeholder": "Email",
            "password_placeholder": "Hasło",
            "register_success": "Rejestracja zakończona. Możesz się zalogować."
        },
        "nav": {
            "dashboard": "Panel",
            "activity": "Aktywność",
            "transactions": "Transakcje",
            "documents": "Dokumenty",
            "reports": "Raporty",
            "marketplace": "Marketplace",
            "submission": "Wysyłka podatków",
            "profile": "Profil",
            "admin": "Admin"
        },
        "dashboard": {
            "title": "Główny panel",
            "description": "Witamy w Twoim Self Assessment.",
            "tax_estimator_title": "Kalkulator podatku (UK)",
            "tax_estimator_button": "Oblicz podatek",
            "tax_estimator_result_title": "Szacowany podatek za",
            "total_income_label": "Łączny dochód",
            "allowable_expenses_label": "Koszty dopuszczalne",
            "disallowable_expenses_label": "Koszty niedopuszczalne",
            "taxable_profit_label": "Dochód do opodatkowania",
            "income_tax_due_label": "Podatek dochodowy",
            "class2_nic_label": "NIC klasa 2",
            "class4_nic_label": "NIC klasa 4",
            "estimated_tax_due_label": "Szacowany podatek",
            "cashflow_title": "Prognoza przepływów (następne 30 dni)",
            "cashflow_loading": "Generowanie prognozy...",
            "readiness_title": "Gotowość podatkowa",
            "readiness_description": "Pokazuje, jak przygotowane są dane do Self Assessment.",
            "readiness_score_label": "Wynik gotowości",
            "readiness_missing_categories": "Nieskategoryzowane transakcje:",
            "readiness_missing_business_use": "Brak % użycia biznesowego w wydatkach:",
            "readiness_actions_title": "Następne działania",
            "readiness_action_categories": "Skategoryzuj pozostałe transakcje.",
            "readiness_action_business_use": "Dodaj % użycia biznesowego dla wydatków mieszanych.",
            "readiness_no_transactions": "Brak zaimportowanych transakcji.",
            "readiness_low": "Niska gotowość",
            "readiness_medium": "Średnia gotowość",
            "readiness_high": "Wysoka gotowość",
            "readiness_loading": "Obliczanie gotowości...",
            "action_next_title": "Co dalej?",
            "action_next_description": "Poznaj marketplace z zaufanymi partnerami od ubezpieczeń, księgowości i nie tylko.",
            "action_next_button": "Poznaj usługi partnerskie"
        },
        "activity": {
            "description": "Poniżej zapis ostatnich zdarzeń na koncie.",
            "col_date": "Data",
            "col_action": "Akcja",
            "col_details": "Szczegóły"
        },
        "transactions": {
            "title": "Transakcje",
            "description": "Połącz konto bankowe, aby importować i kategoryzować transakcje.",
            "bank_connections_title": "Połączenia bankowe",
            "connect_button": "Połącz konto bankowe",
            "consent_prompt": "Kliknij link, aby udzielić dostępu w banku:",
            "loading": "Ładowanie transakcji...",
            "recent_title": "Ostatnie transakcje",
            "col_date": "Data",
            "col_description": "Opis",
            "col_amount": "Kwota",
            "col_category": "Kategoria",
            "select_placeholder": "Wybierz...",
            "csv_title": "Import CSV",
            "csv_description": "Załaduj plik CSV, jeśli bank nie jest wspierany.",
            "csv_account_label": "ID konta",
            "csv_account_placeholder": "Wklej UUID konta",
            "csv_upload_button": "Wyślij CSV",
            "csv_uploading": "Wysyłanie...",
            "csv_success": "Import CSV zaakceptowany. Zaimportowano:",
            "csv_skipped_label": "Pominięto:",
            "csv_select_error": "Wybierz plik CSV.",
            "csv_account_error": "ID konta jest wymagane."
        },
        "documents": {
            "description": "Prześlij i zarządzaj paragonami oraz fakturami.",
            "upload_title": "Prześlij dokument",
            "upload_button": "Prześlij",
            "uploading_button": "Wysyłanie...",
            "col_filename": "Nazwa pliku",
            "col_status": "Status",
            "col_vendor": "Dostawca",
            "col_amount": "Kwota",
            "col_uploaded_at": "Data przesłania",
            "search_title": "Semantyczne wyszukiwanie dokumentów",
            "search_description": "Zadaj pytanie o dokumenty w języku naturalnym.",
            "search_placeholder": "np. 'gdzie kupiłem kawę w zeszłym miesiącu?'",
            "search_button": "Szukaj",
            "search_results_title": "Wyniki wyszukiwania",
            "search_similarity_label": "Wskaźnik podobieństwa:",
            "all_documents_title": "Wszystkie przesłane dokumenty",
            "select_file_error": "Najpierw wybierz plik.",
            "upload_success_prefix": "Plik przesłany:"
        },
        "reports": {
            "description": "Twórz raporty na podstawie danych finansowych.",
            "cadence_title": "Częstotliwość raportowania",
            "cadence_description": "Na podstawie obrotu ustal, czy potrzebne są raporty kwartalne.",
            "cadence_turnover_label": "Obrót (ostatnie 12 miesięcy)",
            "cadence_threshold_label": "Próg kwartalny",
            "cadence_quarterly_required": "Wymagane raportowanie kwartalne.",
            "cadence_monthly_ok": "Wystarczy raportowanie miesięczne.",
            "monthly_title": "Podsumowanie miesięczne",
            "monthly_description": "Miesięczne podsumowanie zysku.",
            "monthly_button": "Generuj podsumowanie miesięczne",
            "quarterly_title": "Podsumowanie kwartalne (Pro)",
            "quarterly_description": "Generuj podsumowanie kwartalne, jeśli wymagane.",
            "quarterly_button": "Generuj podsumowanie kwartalne",
            "profit_loss_title": "Zysk i strata (Pro)",
            "profit_loss_description": "Generuj P&L za ostatni kwartał.",
            "profit_loss_button": "Generuj P&L",
            "tax_year_title": "Podsumowanie roku podatkowego (Pro)",
            "tax_year_description": "Podsumowanie dla roku podatkowego UK.",
            "tax_year_button": "Generuj podsumowanie roku",
            "mortgage_title": "Raport hipoteczny",
            "mortgage_description": "Generuj PDF z dochodami z ostatnich 12 miesięcy. Przydatne przy kredycie.",
            "generate_button": "Generuj raport",
            "generating_button": "Generowanie...",
            "pro_required": "Wymagana subskrypcja Pro.",
            "error_generic": "Nie udało się wygenerować raportu."
        },
        "marketplace": {
            "description": "Poznaj marketplace z zaufanymi partnerami w księgowości, ubezpieczeniach i więcej.",
            "request_button": "Poproś o kontakt",
            "handoff_confirmation": "Twoja prośba została wysłana do"
        },
        "submission": {
            "description": "Oblicz i wyślij deklarację podatkową do HMRC.",
            "form_title": "Nowa deklaracja Self Assessment UK",
            "submit_button": "Oblicz i wyślij do HMRC",
            "success_title": "Wysyłka zainicjowana pomyślnie",
            "submitting": "Wysyłanie...",
            "status_label": "Status wysyłki",
            "id_label": "ID wysyłki HMRC",
            "reminder_note": "Dodaliśmy przypomnienie w kalendarzu o terminie płatności 31 stycznia."
        },
        "profile": {
            "title": "Twój profil",
            "description": "Sprawdź i zaktualizuj dane profilu.",
            "empty_profile": "Nie znaleziono profilu. Zapisz, aby go utworzyć.",
            "saved_message": "Profil zapisany pomyślnie!",
            "first_name": "Imię",
            "last_name": "Nazwisko",
            "date_of_birth": "Data urodzenia"
        },
        "subscription": {
            "title": "Subskrypcja",
            "description": "Zarządzaj planem i dniem zamknięcia miesiąca.",
            "plan_label": "Plan",
            "plan_free": "Bezpłatny",
            "plan_pro": "Pro",
            "close_day_label": "Dzień zamknięcia miesiąca (1-28)",
            "status_label": "Status",
            "cycle_label": "Cykl rozliczeniowy",
            "period_label": "Bieżący okres",
            "update_button": "Aktualizuj subskrypcję",
            "updated_message": "Subskrypcja zaktualizowana."
        },
        "admin": {
            "description": "Zarządzaj użytkownikami i ustawieniami systemu.",
            "form_title": "Dezaktywacja użytkownika",
            "deactivate_button": "Dezaktywuj użytkownika",
            "email_placeholder": "user.email@example.com",
            "deactivated_message": "Użytkownik dezaktywowany:"
        }
    }
}

# --- Endpoints ---

@app.get(
    "/translations/{locale}/{component}",
    response_model=Dict[str, str],
    summary="Get translations for a component",
    deprecated=True
)
async def get_translations_by_component(
    locale: str = Path(..., example="en-GB"),
    component: str = Path(..., example="login")
):
    """
    Retrieves a key-value map for a given locale and component.
    """
    if locale_data := fake_translations_db.get(locale):
        if component_data := locale_data.get(component):
            return component_data

    raise HTTPException(
        status_code=status.HTTP_404_NOT_FOUND,
        detail=f"Translations for locale '{locale}' and component '{component}' not found."
    )

@app.get(
    "/translations/{locale}/all",
    response_model=Dict[str, Dict[str, str]],
    summary="Get all translations for a locale"
)
async def get_all_translations_for_locale(locale: str = Path(..., example="en-GB")):
    """
    Retrieves all translation namespaces for a given locale.
    This is useful for loading all strings for a single-page application.
    """
    if locale_data := fake_translations_db.get(locale):
        return locale_data

    raise HTTPException(
        status_code=status.HTTP_404_NOT_FOUND,
        detail=f"Translations for locale '{locale}' not found."
    )
