# Type stubs for crud module
from typing import Any, Optional, List, Dict
from sqlalchemy.ext.asyncio import AsyncSession
from . import schemas, models

async def get_user_profile(db: AsyncSession, user_id: str) -> Optional[Any]: ...
async def create_user_profile(db: AsyncSession, user_profile: schemas.UserProfileCreate, tenant_id: str) -> Any: ...
async def update_user_profile(db: AsyncSession, user_id: str, user_profile_update: schemas.UserProfileUpdate) -> Any: ...
async def delete_user_profile(db: AsyncSession, user_id: str) -> bool: ...
async def list_user_profiles(db: AsyncSession, skip: int = 0, limit: int = 100) -> List[Any]: ...
async def get_user_profiles_list(db: AsyncSession, skip: int = 0, limit: int = 100) -> List[Any]: ...
async def get_total_users_count(db: AsyncSession) -> int: ...
async def get_active_subscriptions_count(db: AsyncSession) -> int: ...
async def get_subscription_plan_distribution(db: AsyncSession) -> Dict[str, int]: ...

# Existing functions
async def get_profile_by_user_id(db: AsyncSession, user_id: str) -> Optional[models.UserProfile]: ...
async def get_or_create_profile(db: AsyncSession, user_id: str) -> models.UserProfile: ...
async def create_or_update_profile(db: AsyncSession, user_id: str, profile: schemas.UserProfileUpdate) -> models.UserProfile: ...
async def update_subscription(db: AsyncSession, user_id: str, update: schemas.SubscriptionUpdate) -> models.UserProfile: ...
