{
 "title": "FastAPI Overview",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Requests per Second (RPS)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(http_requests_total{job=\"fintech-app\"}[5m])",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "Server Errors (5xx)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(http_requests_total{job=\"fintech-app\", status=~\"5..\"}[5m])",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "Request Latency (95th percentile)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_requests_latency_seconds_bucket{job=\"fintech-app\"}[5m])) by (le, handler))",
     "legendFormat": "{{handler}}"
    }
   ]
  }
 ]
}